# Generated by Django 3.0.3 on 2020-03-15 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
