# Generated by Django 3.0.3 on 2020-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0002_auto_20200227_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
