# Generated by Django 3.0.3 on 2020-03-07 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0003_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
