# Generated by Django 3.0.3 on 2020-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0004_auto_20200307_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_commentable',
            field=models.BooleanField(default=False),
        ),
    ]
